spring.datasource.url=jdbc:postgresql://localhost:5432/transa
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.enabled=false
spring.aop.auto=true
spring.aop.proxy-target-class=true
logging.level.org.springframework.boot.autoconfigure.logging=INFO


